---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: /home///openshift
mirror:
  platform:
    graph: true
    channels:
      - name: stable-4.13
        type: ocp
        minVersion: 4.13.18
        shortestPath: true
      - name: stable-4.14
        type: ocp
        shortestPath: true
      - name: stable-4.15
        type: ocp
        shortestPath: true
      - name: stable-4.16
        type: ocp
        shortestPath: true
  operators:
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.14
      packages:
        - name: minio-operator
          channels:
            - name: stable